const actionTypes = {
  CAN_CASTLE: "CAN_CASTLE",
  NEW_MOVE: "NEW_MOVE",
  GENERATE_CANDIDATE_MOVES: "GENERATE_CANDIDATE_MOVES",
  CLEAR_CANDIDATE_MOVES: "CLEAR_CANDIDATE_MOVES",
  OPEN_PROMOTION: "OPEN_PROMOTION",
  CLOSE_PROMOTION: "CLOSE_PROMOTION",
};
export default actionTypes;
